/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraespecial;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author desarrollador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
        tfNumero2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbFactorial = new javax.swing.JRadioButton();
        rbCalcularMCM = new javax.swing.JRadioButton();
        rbSumarPrimos = new javax.swing.JRadioButton();
        rbVerificarPrimo = new javax.swing.JRadioButton();
        jlTituloCampo = new javax.swing.JLabel();
        tfNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCalcularOperacion = new javax.swing.JButton();
        lbResultadoCalculo = new javax.swing.JLabel();
        jlTituloCampo2 = new javax.swing.JLabel();
        tfNumero2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Seleccione una operacion");

        grupoBotones.add(rbFactorial);
        rbFactorial.setText("Factorial");
        rbFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFactorialActionPerformed(evt);
            }
        });

        grupoBotones.add(rbCalcularMCM);
        rbCalcularMCM.setText("Calcular Mínimo Común Múltiplo");
        rbCalcularMCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCalcularMCMActionPerformed(evt);
            }
        });

        grupoBotones.add(rbSumarPrimos);
        rbSumarPrimos.setText("Sumar N numeros Primos");
        rbSumarPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSumarPrimosActionPerformed(evt);
            }
        });

        grupoBotones.add(rbVerificarPrimo);
        rbVerificarPrimo.setText("Verificar número primo");
        rbVerificarPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerificarPrimoActionPerformed(evt);
            }
        });

        tfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero1ActionPerformed(evt);
            }
        });

        jLabel2.setText("RESULTADO:");

        btnCalcularOperacion.setText("Calcular");
        btnCalcularOperacion.setEnabled(false);
        btnCalcularOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularOperacionActionPerformed(evt);
            }
        });

        tfNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(lbResultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnCalcularOperacion))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTituloCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSumarPrimos)
                            .addComponent(rbFactorial))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCalcularMCM)
                            .addComponent(rbVerificarPrimo)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFactorial)
                    .addComponent(rbCalcularMCM))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSumarPrimos)
                    .addComponent(rbVerificarPrimo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlTituloCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lbResultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularOperacion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFactorialActionPerformed
        // TODO add your handling code here:
        updateForm("Número", "");
    }//GEN-LAST:event_rbFactorialActionPerformed

    private void rbSumarPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSumarPrimosActionPerformed
        // TODO add your handling code here:
        updateForm("Cantidad primos", "");
    }//GEN-LAST:event_rbSumarPrimosActionPerformed

    private void tfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero1ActionPerformed

    private void btnCalcularOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularOperacionActionPerformed
        // TODO add your handling code here:
        lbResultadoCalculo.setText("");
        String input1 = tfNumero1.getText();
        String input2 = tfNumero2.getText();
        Operacion operacion = new Operacion();
        try {
            validarPorExpresionRegular(input1 , "numero1");//Se valida el input de la izquierda
             int numero = Integer.parseInt(input1);
         if(rbFactorial.isSelected()){
             float resultado = operacion.factorial(numero);
             lbResultadoCalculo.setText(String.valueOf(String.format("%d! = %.0f %n", numero, resultado)));
         }else if(rbSumarPrimos.isSelected()){
             float resultado = operacion.sumarPrimos(numero);
             lbResultadoCalculo.setText(String.valueOf(String.format("%.0f %n", resultado)));
         }else if(rbVerificarPrimo.isSelected()){
             boolean resultado = operacion.verificarPrimo(numero);
             String mensaje = resultado ? "El numero "+input1 +" es primo." : "El numero " +input1+" no es primo.";
             lbResultadoCalculo.setText(mensaje);
         }else if(rbCalcularMCM.isSelected()){
             validarPorExpresionRegular(input2 , "numero 2");
             int numero2 = Integer.parseInt(input2);
             int resultado = operacion.calcularMCM(numero, numero2);
             lbResultadoCalculo.setText(String.valueOf(resultado));
         }
        }catch (Exception e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_btnCalcularOperacionActionPerformed

    private void rbVerificarPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerificarPrimoActionPerformed
        // TODO add your handling code here:
        updateForm("Número", "");
    }//GEN-LAST:event_rbVerificarPrimoActionPerformed

    private void rbCalcularMCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCalcularMCMActionPerformed
        // TODO add your handling code here:
        updateForm("Número 1", "Número 2");
    }//GEN-LAST:event_rbCalcularMCMActionPerformed

    private void tfNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero2ActionPerformed

    private void validarPorExpresionRegular(String valor, String titulo) throws Exception{
        System.out.println("Paso todas");
        Pattern patron = Pattern.compile("^[1-9][0-9]*$");
        Matcher coincidencia = patron.matcher(valor);
        String regex = "^[a-zA-Z\\p{Punct}]+$";
        boolean tieneTexto = valor.matches(regex);
        String mensaje = titulo.equals("numero1") ? jlTituloCampo.getText() : jlTituloCampo2.getText();
        if(tieneTexto){
            throw new Exception(mensaje+": debe ser un número positivo mayor a 0.");
        }
        if(!coincidencia.find()){
            throw new Exception(mensaje+": debe ser un número positivo mayor a 0.");
        } 
    }
    private void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void updateForm(String tituloCampo1, String tituloCampo2){
        System.out.println(tituloCampo1);
        if(!tituloCampo2.isEmpty()){
            jlTituloCampo2.setText(tituloCampo2);
            tfNumero2.setVisible(true);
            tfNumero2.setText("");
        }else{
            jlTituloCampo2.setText("");
            tfNumero2.setVisible(false);
        }
        
        btnCalcularOperacion.setEnabled(false);
        jlTituloCampo.setText("");
        jlTituloCampo.setText(tituloCampo1);
        btnCalcularOperacion.setEnabled(true);
        if(rbFactorial.isSelected()){

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularOperacion;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlTituloCampo;
    private javax.swing.JLabel jlTituloCampo2;
    private javax.swing.JLabel lbResultadoCalculo;
    private javax.swing.JRadioButton rbCalcularMCM;
    private javax.swing.JRadioButton rbFactorial;
    private javax.swing.JRadioButton rbSumarPrimos;
    private javax.swing.JRadioButton rbVerificarPrimo;
    private javax.swing.JTextField tfNumero1;
    private javax.swing.JTextField tfNumero2;
    // End of variables declaration//GEN-END:variables
}
