/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraespecial;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author desarrollador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbFactorial = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rbSumarPrimos = new javax.swing.JRadioButton();
        rbVerificarPrimo = new javax.swing.JRadioButton();
        jlTituloCampo = new javax.swing.JLabel();
        tfNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCalcularOperacion = new javax.swing.JButton();
        lbResultadoCalculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Seleccione una operacion");

        grupoBotones.add(rbFactorial);
        rbFactorial.setText("Factorial");
        rbFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFactorialActionPerformed(evt);
            }
        });

        grupoBotones.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        grupoBotones.add(rbSumarPrimos);
        rbSumarPrimos.setText("Sumar N numeros Primos");
        rbSumarPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSumarPrimosActionPerformed(evt);
            }
        });

        grupoBotones.add(rbVerificarPrimo);
        rbVerificarPrimo.setText("Verificar número primo");
        rbVerificarPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerificarPrimoActionPerformed(evt);
            }
        });

        tfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero1ActionPerformed(evt);
            }
        });

        jLabel2.setText("RESULTADO:");

        btnCalcularOperacion.setText("Calcular");
        btnCalcularOperacion.setEnabled(false);
        btnCalcularOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularOperacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbFactorial)
                .addGap(151, 151, 151)
                .addComponent(jRadioButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbSumarPrimos)
                .addGap(36, 36, 36)
                .addComponent(rbVerificarPrimo))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jlTituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(tfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(lbResultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnCalcularOperacion))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFactorial)
                    .addComponent(jRadioButton2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSumarPrimos)
                    .addComponent(rbVerificarPrimo))
                .addGap(28, 28, 28)
                .addComponent(jlTituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lbResultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCalcularOperacion))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFactorialActionPerformed
        // TODO add your handling code here:
        updateForm("Número", "");
    }//GEN-LAST:event_rbFactorialActionPerformed

    private void rbSumarPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSumarPrimosActionPerformed
        // TODO add your handling code here:
        updateForm("Cantidad primos", "");
    }//GEN-LAST:event_rbSumarPrimosActionPerformed

    private void tfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero1ActionPerformed

    private void btnCalcularOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularOperacionActionPerformed
        // TODO add your handling code here:
        lbResultadoCalculo.setText("");
        String input1 = tfNumero1.getText();
        Operacion operacion = new Operacion();
        try {
            validarPorExpresionRegular(input1 , "numero");//Se valida el input de la izquierda
            //validarPorExpresionRegular(valorDerecho , tituloDerecha);////Se valida el input de la deceha
             int numero = Integer.parseInt(input1);
             System.out.println(operacion.verificarPrimo(numero));
         if(rbFactorial.isSelected()){
             float resultado = operacion.factorial(numero);
             lbResultadoCalculo.setText(String.valueOf(String.format("%d! = %.0f %n", numero, resultado)));
         }else if(rbSumarPrimos.isSelected()){
             float resultado = operacion.sumarPrimos(numero);
             lbResultadoCalculo.setText(String.valueOf(String.format("%.0f %n", resultado)));
         }else if(rbVerificarPrimo.isSelected()){
             boolean resultado = operacion.verificarPrimo(numero);
             String mensaje = resultado ? "El numero "+input1 +" es primo." : "EL numero " +input1+" no es primo.";
             lbResultadoCalculo.setText(mensaje);
         }
        }catch (Exception e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_btnCalcularOperacionActionPerformed

    private void rbVerificarPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerificarPrimoActionPerformed
        // TODO add your handling code here:
        updateForm("Número", "");
    }//GEN-LAST:event_rbVerificarPrimoActionPerformed

    private void validarPorExpresionRegular(String valor, String titulo) throws Exception{
        System.out.println("Paso todas");
        Pattern patron = Pattern.compile("^[1-9][0-9]*$");
        Matcher coincidencia = patron.matcher(valor);
        String regex = "^[a-zA-Z\\p{Punct}]+$";
        boolean tieneTexto = valor.matches(regex);
        if(tieneTexto){
            throw new Exception(titulo+": solo se acepta números positivos.");
        }
        if(!coincidencia.find()){
            throw new Exception(titulo+": debe ser un número positivo mayor a 1.");
        } 
    }
    private void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void updateForm(String tituloCampo1, String tituloCampo2){
        System.out.println(tituloCampo1);
        btnCalcularOperacion.setEnabled(false);
        jlTituloCampo.setText("");
        jlTituloCampo.setText(tituloCampo1);
        btnCalcularOperacion.setEnabled(true);
        if(rbFactorial.isSelected()){

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularOperacion;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jlTituloCampo;
    private javax.swing.JLabel lbResultadoCalculo;
    private javax.swing.JRadioButton rbFactorial;
    private javax.swing.JRadioButton rbSumarPrimos;
    private javax.swing.JRadioButton rbVerificarPrimo;
    private javax.swing.JTextField tfNumero1;
    // End of variables declaration//GEN-END:variables
}
